[package]
name = "soros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty_assertions = "1.4.0"
thiserror = "1.0.58"
rand = "0.9.0-alpha.1"
